MyDentist/Models/ArticleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyDentist.Models
{
    public class ArticleViewModel
    {
        [Display(Name = "ID Article")]
        public int ID_Article { get; set; }
        [Required]

        [Display(Name = "Title")]
        public string Tittle { get; set; }

        [Display(Name = "Writer Name")]
        [Required]
        public string Writer_name { get; set; }

        [Required]
        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Release_date { get; set; }

        [Display(Name = "Content")]
        [AllowHtml]
        [Required]
        public string Content { get; set; }

        [Display(Name = "Picture")]
        [Required]
        public byte[] Picture { get; set; }
    }
}

MyDentist/Controllers/ArticleController.cs
using MyDentist.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyDentist.Repositories;
using PagedList;

namespace MyDentist.Controllers
{
    [RoutePrefix("Index")]
    [ValidateInput(false)]
    public class ArticleController : Controller
    {
        private db_mydentistEntities1 db = new db_mydentistEntities1();
        private const int pageSize = 5;
        // GET: Article
        [Authorize]
        public ActionResult Index(int? page, string searching)
        {
            int pageNumber = (page ?? 1);
            return View((db.tbl_Article.Where(x => x.Tittle.Contains(searching) || searching == null)).OrderByDescending(s => s.ID_Article).ToList().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult IndexDentist(int? page, string searching)
        {
            int pageNumber = (page ?? 1);
            return PartialView((db.tbl_Article.Where(x => x.Tittle.Contains(searching) || searching == null)).OrderByDescending(s => s.ID_Article).ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: Article/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            return View(db.tbl_Article.Where(x => x.ID_Article == id).FirstOrDefault());
        }

        [Authorize]
        public ActionResult DetailsDentist(int id)
        {
            return PartialView(db.tbl_Article.Where(x => x.ID_Article == id).FirstOrDefault());
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Article/Create
        [Route("Create")]
        [HttpPost]
        [Authorize]
        public ActionResult Create(ArticleViewModel model)
        {
            try
            {
                HttpPostedFileBase file = Request.Files["ImageData"];
                ArticleRepositories service = new ArticleRepositories();
                int i = service.UploadImageInDataBase(file, model);
                if (i == 1)
                {
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch
            {
                return View();
            }
        }

        // GET: Article/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Article/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Article/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Article/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult RetrieveImage(int id)
        {
            byte[] cover = GetImageFromDataBase(id);
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        public byte[] GetImageFromDataBase(int Id)
        {
            var q = from temp in db.tbl_Article where temp.ID_Article == Id select temp.Picture;
            byte[] cover = q.First();
            return cover;
        }

        protected override JsonResult Json(object data, string contentType, System.Text.Encoding contentEncoding, JsonRequestBehavior behavior)
        {
            return new JsonResult()
            {
                Data = data,
                ContentType = contentType,
                ContentEncoding = contentEncoding,
                JsonRequestBehavior = behavior,
                MaxJsonLength = Int32.MaxValue
            };
        }

        [HttpGet]
        public JsonResult GetArticle()
        {
            var content = db.tbl_Article.Select(s => new
            {
                s.ID_Article,
                s.Tittle,
                s.Picture,
                s.Content,
                s.Release_date,
                s.Writer_name
            });

            List<ArticleViewModel> contentModel = content.Select(item => new ArticleViewModel()
            {
                ID_Article = item.ID_Article,
                Tittle = item.Tittle,
                Picture = item.Picture,
                Content = item.Content,
                Release_date = item.Release_date,
                Writer_name = item.Writer_name
            }).OrderByDescending(s => s.ID_Article).ToList();
            return Json(contentModel, JsonRequestBehavior.AllowGet);
        }
    }
}

MyDentist/Views/Article/Create.cshtml
@model MyDentist.Models.ArticleViewModel
@{
    ViewBag.Title = "Create";
}

<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/ckeditor/adapters/jquery.js"></script>


<script type="text/javascript">
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png', 'gif', 'bmp'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png', '.gif', '.bmp' formats are allowed.");
        }
    }
</script>

@using (Html.BeginForm("Create", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="text-align-center"><h4>Create New Content</h4></div>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Tittle, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Tittle, new { @class = "form-control", placeholder = "Content Title" })
                @Html.ValidationMessageFor(model => model.Tittle)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageData" id="ImageData" onchange="fileCheck(this);" />
                @Html.ValidationMessageFor(model => model.Picture)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer_name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Writer_name, new { @class = "form-control", placeholder = "Writer Name" })
                @Html.ValidationMessageFor(model => model.Writer_name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { @class = "ckeditor", placeholder = "Content Description" })
                @Html.ValidationMessageFor(model => model.Content)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

MyDentist/Views/Article/Details.cshtml
@{
    Layout = null;
}
@model MyDentist.Models.tbl_Article

<!DOCTYPE html>
<html lang="en">
<head>

    <title>MyDentist - Article Page</title>
    @Styles.Render("~/cssing/css")

    <style>
        .pic {
            max-width: 80%;
            height: auto;
        }
    </style>
</head>

<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
    @Html.Partial("Navigation")
    <!-- NEWS DETAIL -->
    <section id="news-detail" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row">

                <div class="col-md-8 col-sm-7">
                    <!-- NEWS THUMB -->
                    <div class="news-detail-thumb">
                        <div class="news-image">
                            <div class="center-block">
                                <img src="@Url.Action("RetrieveImage", new { id = Model.ID_Article})" class="pic" alt="" />
                            </div>
                        </div>
                        <h3>@Html.DisplayFor(model => model.Tittle)</h3>
                        <p>@Html.Raw(Model.Content)</p>


                        <p>Nunc eget ex sed nisl rhoncus lacinia. Vestibulum porta lectus at est placerat, nec commodo purus dignissim. Suspendisse ac quam in metus laoreet auctor ac quis enim.</p>
                        <div class="news-social-share">
                            <h4>Share this article</h4>
                            <a href="#" class="btn btn-primary"><i class="fa fa-facebook"></i>Facebook</a>
                            <a href="#" class="btn btn-success"><i class="fa fa-twitter"></i>Twitter</a>
                            <a href="#" class="btn btn-danger"><i class="fa fa-google-plus"></i>Google+</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-5">
                    <div class="news-sidebar">
                        <div class="news-author">
                            <h4>About the Article</h4>
                            <p>@Html.DisplayFor(model => model.Writer_name)</p>
                            <p>@Html.DisplayFor(model => model.Release_date)</p>
                        </div>

                        <div class="news-categories">
                            <h4>Categories</h4>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Dental</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Cardiology</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Health</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Consultant</a></li>
                        </div>

                        <div class="news-ads sidebar-ads">
                            <h4>Sidebar Banner Ad</h4>
                        </div>

                        <div class="news-tags">
                            <h4>Tags</h4>
                            <li><a href="#">Pregnancy</a></li>
                            <li><a href="#">Health</a></li>
                            <li><a href="#">Consultant</a></li>
                            <li><a href="#">Medical</a></li>
                            <li><a href="#">Doctors</a></li>
                            <li><a href="#">Social</a></li>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
</body>
</html>
@Html.Partial("Footer")

<!-- SCRIPTS -->
@Scripts.Render("~/bundles/Content")
@Scripts.Render("~/bundles/bootstrap")

MyDentist/Views/Article/DetailsDentist.cshtml
@{
    Layout = null;
}
@model MyDentist.Models.tbl_Article

<!DOCTYPE html>
<html lang="en">
<head>

    <title>MyDentist - Article Page</title>
    @Styles.Render("~/cssing/css")

    <style>
        .pic {
            max-width: 80%;
            height: auto;
        }
    </style>
</head>

<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">
    @Html.Partial("NavigationDentist")
    <!-- NEWS DETAIL -->
    <section id="news-detail" data-stellar-background-ratio="0.5">
        <div class="container">
            <div class="row">

                <div class="col-md-8 col-sm-7">
                    <!-- NEWS THUMB -->
                    <div class="news-detail-thumb">
                        <div class="news-image">
                            <div class="center-block">
                                <img src="@Url.Action("RetrieveImage", new { id = Model.ID_Article})" class="pic" alt="" />
                            </div>
                        </div>
                        <h3>@Html.DisplayFor(model => model.Tittle)</h3>
                        <p>@Html.Raw(Model.Content)</p>


                        <p>Nunc eget ex sed nisl rhoncus lacinia. Vestibulum porta lectus at est placerat, nec commodo purus dignissim. Suspendisse ac quam in metus laoreet auctor ac quis enim.</p>
                        <div class="news-social-share">
                            <h4>Share this article</h4>
                            <a href="#" class="btn btn-primary"><i class="fa fa-facebook"></i>Facebook</a>
                            <a href="#" class="btn btn-success"><i class="fa fa-twitter"></i>Twitter</a>
                            <a href="#" class="btn btn-danger"><i class="fa fa-google-plus"></i>Google+</a>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-sm-5">
                    <div class="news-sidebar">
                        <div class="news-author">
                            <h4>About the Article</h4>
                            <p>@Html.DisplayFor(model => model.Writer_name)</p>
                            <p>@Html.DisplayFor(model => model.Release_date)</p>
                        </div>

                        <div class="news-categories">
                            <h4>Categories</h4>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Dental</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Cardiology</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Health</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i> Consultant</a></li>
                        </div>

                        <div class="news-ads sidebar-ads">
                            <h4>Sidebar Banner Ad</h4>
                        </div>

                        <div class="news-tags">
                            <h4>Tags</h4>
                            <li><a href="#">Pregnancy</a></li>
                            <li><a href="#">Health</a></li>
                            <li><a href="#">Consultant</a></li>
                            <li><a href="#">Medical</a></li>
                            <li><a href="#">Doctors</a></li>
                            <li><a href="#">Social</a></li>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
</body>
</html>
@Html.Partial("Footer")

<!-- SCRIPTS -->
@Scripts.Render("~/bundles/Content")
@Scripts.Render("~/bundles/bootstrap")

MyDentist/Views/Article/Edit.cshtml
@model MyDentist.Models.tbl_Article

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Article)

        <div class="form-group">
            @Html.LabelFor(model => model.Tittle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tittle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tittle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writer_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writer_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Release_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Release_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Release_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyDentist/Views/Article/EditArticle.cshtml
@model MyDentist.Models.tbl_Article

@{
    ViewBag.Title = "EditArticle";
}

<h2>EditArticle</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_Article</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Article)

        <div class="form-group">
            @Html.LabelFor(model => model.Tittle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tittle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tittle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Writer_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Writer_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Writer_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Release_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Release_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Release_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyDentist/Views/Article/Index.cshtml
@using PagedList.Mvc
@model PagedList.IPagedList<MyDentist.Models.tbl_Article>
@{
    ViewBag.Title = "Article";
}
<link href="~/Content/PagedList.css" rel="stylesheet" />
<style>


    table {
        width: 60%;
        border-collapse: collapse;
    } 
    table tr {
        border: solid thin;
    }

        table tr td {
            width: 20%;
        }

    #pager {
        padding-left: 5%;
        
    }

        #pager p {
            margin-left: 5%;
        }  

    input::-webkit-input-placeholder {
        opacity: 0.5;
    }

    input:-moz-placeholder {
        opacity: 0.5;
    }

    input:-ms-input-placeholder {
        opacity: 0.5;
    }

    .input100 {
        font-family: Ubuntu-Bold;
        font-size: 15px;
        color: #1b3815;
        /* line-height: 1.2; */
        position: relative;
        display: block;
        width: 200px;
        height: 30px;
        background: #ebebeb;
        border-radius: 27px;
        padding: 0 35px 0 35px;
    }

    .btn-info {
        color: #fff;
        background-color: #5bc0de;
        border-color: #46b8da;
        width: 80px;
        height: 30px;
        border-radius: 99px;
    }

</style>

<div class="text-align-center">
    <h2>@ViewBag.Title</h2>
</div>

<br />
@using (Html.BeginForm("Index", "Article", FormMethod.Get))
{

    @Html.TextBox("searching", null, new { @class = "input100 fa-search", placeholder = "Search Article" })
    <input class="btn-info m-t-10" type="submit" value="Search" />
}
<br />
<br />

<table class="table table-bordered">
    @if (Model.Count() == 0)
    {
        <div style="color:red">
            No Match Any Article
        </div>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="col-md-4 col-sm-6">
                <!-- NEWS THUMB -->
                <div class="news-thumb wow fadeInUp" data-wow-delay="0.4s">
                    <a href="news-detail.html">
                        <!--<img src="@Url.Content("~/images/news-image1.jpg")" class="img-responsive" alt="">-->
                        <img src="@Url.Action("RetrieveImage", new { id = item.ID_Article })" alt="" class="img-responsive" />
                    </a>
                    <div class="news-info">
                        <h5>By : @Html.DisplayFor(modelItem => item.Writer_name)</h5>
                        <span>@Html.DisplayFor(modelItem => item.Release_date)</span>
                        <h3><a href="news-detail.html">@Html.ActionLink(item.Tittle, "Details", "Article", new { id = item.ID_Article }, null)</a></h3>
                    </div>
                </div>
            </div>
        }
    }
</table >
<div id="pager">
    <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>




<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap.min.css" />

@section scripts{
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap.min.js"></script>


}

MyDentist/Views/Article/IndexDentist.cshtml
@{
    Layout = null;
}
@using PagedList.Mvc
@model PagedList.IPagedList<MyDentist.Models.tbl_Article>
@Styles.Render("~/cssing/css")

<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

    @Html.Partial("NavigationDentist")
    @{
        ViewBag.Title = "Article";
    }
    <style>

        table {
            width: 60%;
            border-collapse: collapse;
        }

            table tr {
                border: solid thin;
            }

                table tr td {
                    width: 20%;
                }

        #pager {
            padding-left: 5%
        }

            #pager p {
                margin-left: 5%;
            }

        input::-webkit-input-placeholder {
            opacity: 0.5;
        }

        input:-moz-placeholder {
            opacity: 0.5;
        }

        input:-ms-input-placeholder {
            opacity: 0.5;
        }

        .input100 {
            font-family: Ubuntu-Bold;
            font-size: 15px;
            color: #1b3815;
            /* line-height: 1.2; */
            position: relative;
            display: block;
            width: 200px;
            height: 30px;
            background: #ebebeb;
            border-radius: 27px;
            padding: 0 35px 0 35px;
        }

        .btn-info {
            color: #fff;
            background-color: #5bc0de;
            border-color: #46b8da;
            width: 80px;
            height: 30px;
            border-radius: 99px;
        }
    </style>

    <div class="container">
        <div class="row">

            <div class="text-align-center">
                <h2>@ViewBag.Title</h2>
            </div>

            <p>
                @Html.ActionLink("Create New Page Content", "Create", null, new { @class = "btn btn-primary" })
            </p>
            <br />
            @using (Html.BeginForm("IndexDentist", "Article", FormMethod.Get))
            {
                @Html.TextBox("searching", null, new { @class = "input100", placeholder = "Article Title" })<input class="btn-info m-t-10" type="submit" value="Search" />
            }
            <br /><br />
            <table class="table table-borderless">
                @if (Model.Count() == 0)
    {
        <div style="color:red">
            No Match Any Article
        </div>
    }
    else
    {
        foreach (var item in Model)
        {
            <div class="col-md-4 col-sm-6">
                <!-- NEWS THUMB -->
                <div class="news-thumb wow fadeInUp" data-wow-delay="0.4s">
                    <a href="news-detail.html">
                        <!--<img src="@Url.Content("~/images/news-image1.jpg")" class="img-responsive" alt="">-->
                        <img src="@Url.Action("RetrieveImage", new { id = item.ID_Article })" alt="" class="img-responsive" />
                    </a>
                    <div class="news-info">
                        <h5>By : @Html.DisplayFor(modelItem => item.Writer_name)</h5>
                        <span>@Html.DisplayFor(modelItem => item.Release_date)</span>
                        <h3><a href="news-detail.html">@Html.ActionLink(item.Tittle, "Details", "Article", new { id = item.ID_Article }, null)</a></h3>
                    </div>
                </div>
            </div>
        }
    }
            </table>
            <div id="pager">
                <p> Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</p>
                @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
            </div>
        </div>
    </div>
</body>
@Html.Partial("Footer")

<!-- SCRIPTS -->
@Scripts.Render("~/bundles/Content")
@Scripts.Render("~/bundles/bootstrap")